spring.application.name=motordesk-backend

#Database connection
spring.datasource.url = jdbc:postgresql://localhost:5432/motordesk
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

#JWT Key
jwt.secret=${JWT_SECRET}

#Auto create database tables using entities
spring.jpa.hibernate.ddl-auto=update
